//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace С1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Archiv_dogovor = new HashSet<Archiv_dogovor>();
            this.Dogovor = new HashSet<Dogovor>();
        }
    
        public int ID_Client { get; set; }
        public string Name_ { get; set; }
        public string Father_name { get; set; }
        public string Surname { get; set; }
        public string Tel { get; set; }
        public System.DateTime BD { get; set; }
        public string Seria_pasport { get; set; }
        public string Number_pasport { get; set; }
        public string Vudan { get; set; }
        public string INN { get; set; }
        public string Propiska { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Archiv_dogovor> Archiv_dogovor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dogovor> Dogovor { get; set; }
    }
}
