//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace С1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dogovor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dogovor()
        {
            this.Prodlenie = new HashSet<Prodlenie>();
        }
    
        public int ID_Dogovor { get; set; }
        public int Client_Id { get; set; }
        public string Predmet { get; set; }
        public decimal Ocenochna_stoimost { get; set; }
        public decimal Vudano { get; set; }
        public decimal Procent { get; set; }
        public string Opisanie { get; set; }
        public System.DateTime Date_Start { get; set; }
        public System.DateTime Date_Finish { get; set; }
        public System.DateTime Date_Start_prod { get; set; }
        public System.DateTime Date_Finish_prod { get; set; }
        public double Ves_All { get; set; }
        public double Ves_zachet { get; set; }
    
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prodlenie> Prodlenie { get; set; }
    }
}
