//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace С1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prodlenie
    {
        public int ID_Prodlenie { get; set; }
        public int Dogovor_Id { get; set; }
        public System.DateTime Date_start_prod { get; set; }
        public System.DateTime Date_finish_prod { get; set; }
        public decimal Price { get; set; }
    
        public virtual Dogovor Dogovor { get; set; }
    }
}
